### ISSUE TITLE
FEATURE REQUEST: Save Audio

### ISSUE THREAD

**Issue by NebularNerd** [n1teshy/yapper-tts#3] opened 2024-11-25 11:01 UTC
Hi there,

This looks a great project and with a couple of quick tweaks it generates some decent results. Would you be able to add the ability to save the audio from the generated speech?

**Comment by Supernovuh** [comment] 2024-11-28 04:54
PLEASE! I would also find use for the same feature. Am experimenting to see if I can get anything to work and will let you know if I find anything

**Comment by Supernovuh** [comment] 2024-11-29 20:48
I added the ability to output audio by editing speaker.py. See the fork on my github to download the updated speaker.py.

**Comment by n1teshy** [comment] 2024-12-05 12:01
Hi guys, sorry for the delay, please take a look at "yapper/speaker.py -> PiperSpeaker.say()" to find out how text is converted to speech and saved to a file, try to replicate that. if that doesn't work out, let me know and I'll drop some code, thank you for stepping in to help @Supernovuh.

Also, @NebularNerd What tweaks did you have to make?

Let me know if the issue is resolved and I'll close it.

**Comment by NebularNerd** [comment] 2024-12-06 09:46
> Also, @NebularNerd What tweaks did you have to make?

I was referring to altering the parameters by following your examples to get a nice sounding voice. Looking at speaker.py I can see that it does save a temp .wav so I can adapt that to my needs. @Supernovuh's solution looks good, a PR to merge it would make it easily accessible for other users.

**Comment by n1teshy** [comment] 2024-12-06 11:21
Hey @Supernovuh, can you raise a PR to merge your changes?

**Comment by Supernovuh** [comment] 2024-12-07 04:18
@n1teshy Done

**Comment by n1teshy** [comment] 2024-12-14 11:31
Hey @NebularNerd , I've added the feature you asked for, PiperSpeaker now has a 'text_to_wave' method to save speech into a wave file. Also, I've added some other fixes, a new, free, LLM API that can be used with the 'GroqEnhancer' class, and there are british voices now, I assume the issue is resolved and I'll close it now. The new features are pushed with the new (0.2.3) release.

**Closed as completed** 2024-12-14 11:31 UTC

**Comment by NebularNerd** [comment] 2024-12-17 16:33
Thanks @n1teshy and @Supernovuh 

I'll give them a try later and see how it goes, I was happy with the output, being able to take a .wav and dump it into a video editor makes things handy for various projects. The British accents will be a nice touch as I'm British.

Merry Xmas to you both. 🎄
